### ISSUE TITLE
question: via queen, dose a test could run in specified browsers?

### ISSUE THREAD

**Issue by fool2fish** [unsetbit/queen#4]
via the examples,  tests will run in all connected browsers
but sometimes, i just want to run test in specified browsers
is there some way to do this?

**Comment by fool2fish** [comment]
by the way, when queen tells browser to load one test file, this request needs queen to be a proxy, why it cannot be sent directly to the thrill server(because thrill will start a server and give the file a url)

**Comment by unsetbit** [comment]
You can determine which browsers run your scripts through the "filter" option in the [workforce configuration](https://github.com/turn/queen/wiki/Writing-Queen-Scripts). For example, if you wanted your script to only run in IE or  Chrome, you could write:

``` javascript
// ... rest of workforce config
filter: function(browser){
    return browser.family === "IE" || browser.family === "Chrome";
},
// rest of workforce config...
```

The `browser` object in this case is the [worker provider attributes object](https://github.com/turn/queen/wiki/Server-API#wiki-workerProvider-attributes) which contains user-agent and browser capability information for you to filter on.

As for your second question, Queen proxies requests from other applications due to [same-origin policies](https://developer.mozilla.org/en-US/docs/JavaScript/Same_origin_policy_for_JavaScript) in browsers. On the front-end, Queen has an application running on the browser which creates an iframe whenever a "worker" is requested. This worker iframe can access the parent document to pick up its socket, which is what allows for bi-directional communication between the worker and the calling application (such as Thrill). 

If the worker was in a document from a different origin than the parent document, they wouldn't be able to communicate, so Queen proxies requested documents to fulfill the same-origin policy. I explored various ways to avoid having to do this, however cross-browser [alternatives for document-to-document messaging](http://benalman.com/projects/jquery-postmessage-plugin/) are too limited for older browsers.

I could see an option in the future where Queen doesn't proxy the document and therefore doesn't try to establish socketed communication between the caller and the front-end script. This leaves it up to the script to establish its own channel of communication directly to the server it originated from. This would allow more resource intensive applications to avoid having Queen proxy their resources at the cost of a more complex worker application. I would be hesitant with doing this with Thrill, because the code that goes in to establishing socketed communication is complex, and should not be resident in a test suite. That being said, there are probably tricks that could avoid that as well (such as more nested iframes).
