### ISSUE TITLE
Best practices for Queen/Thrill/SauceLabs with build server?

### ISSUE THREAD

**Issue by ghost** [unsetbit/queen#6]
Trying to find my way around to put a build environment together. Currently I'm trying to setup Queen/Thrill/SauceLabs to execute unit tests during a build from Jenkins.

Maybe I just misunderstood something but for me the Queen Sauce populator tries to keep the Sauce Labs browser pool current by re-spawning Sauce Lab VM's. At least for me I see new Jobs created in the Sauce Labs overview every 90 s. Each VM will timeout after 90s by default and a new one will be spawned by the Queen populator even if the first VM executed the tests successfully. 

How does this fit into the time based payment of Sauce Labs? 

I'd like to start Queen with the Sauce Labs configuration during build time and trigger the tests by executing thrill during build time. My issue here is that I can start Queen and thrill from the build process, but as long as no worker browser is spawned thrill will return immediately without running any test.

Am I missing something here or do I have to keep Queen running all the time, connected to Sauce Labs and consuming the test time? Or is there a way to synchronize the thrill to Queen connection to be executed only when the first worker from Sauce Labs is online after Queen was started?

**Comment by unsetbit** [comment]
You're right, you're seeing that behavior because Queen is trying to maintain it's browser pool. The short answer is to start Queen when you need it and shut it down when you're done.

The long answer is that Queen is designed to have minimal latency. Other libraries which do similar things to Queen require a new window is started for each job -- that's a lot of overhead that Queen avoids by having browsers actively connected and listening for jobs. This reduces the overhead for running a job from many seconds to milliseconds. That makes a big difference when developing -- for example, we have our tests run on all targeted browsers whenever we save a file, we couldn't do that if we had to wait 10 seconds for the browsers to boot up each time.

Of course, the benefit of an active connection becomes prohibitively costly when using a provider like Sauce Labs or Browser Stack, so you can work around it by starting Queen only when you need it. 

Another solution to your use-case would be to have Queen lazy-spawn disconnected browsers if no jobs are running. That's a feature that doesn't exist yet, but if there's demand for it, that's a good candidate to put into the next version of Queen. And, of course, I would be happy to accept a pull request for it :) .

The synchronization thing is high on my to-do list, I expect to push out a solution withing the next 2 weeks. That's where Queen would have a method of signaling it's readiness so that Thrill (or other applications) know when it's OK to start asking for jobs. The underlying system for that would actually be a stepping stone to getting the lazy-spawning browsers feature, so maybe I can knock two birds with one stone on that one.

As for best practice, when you're dealing with computers outside of your local network, I recommend setting the `stream` [option in Thrill|https://github.com/turn/thrill/wiki/thrill.js-Config-File] to false -- this will significantly reduce network traffic while running your tests by having the browser will only report once when it's done, not while it's working.

**Comment by ghost** [comment]
Great feedback. Really appreciate it. At least it makes clear to me that I understood the basics and I'm on the right track. :) I clearly have to dig into the code to get a better understanding of how everything works together. Looking forward to be able to provide a pull request in the future.

**Comment by unsetbit** [comment]
If you're interested in the code, you should also take a look at the populator plugin itself:   https://github.com/ozanturgut/queen-populator-plugin . Queen actually doesn't have a concept of populators in its code base, it's all encapsulated within the plugin.
